export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const TO_EXTENSION = "TO_EXTENSION";
export const FROM_EXTENSION = "FROM_EXTENSION";
export const INITIALIZATION = "INITIALIZATION";
export const REQUEST = "REQUEST";
